#!/bin/sh

##
# init PostgreSQL data when not exists
#
echo -e "#####\n# Initializing PostgreSQL data and set up host connections ..."
if [ ! -f "/var/lib/postgresql/data/PG_VERSION" ]; then

    echo "postgres" > /var/lib/postgresql/pg.pass
    
    initdb -D /var/lib/postgresql/data --username=postgres --pwfile=/var/lib/postgresql/pg.pass

    rm /var/lib/postgresql/pg.pass

    echo "host all all all md5" >> /var/lib/postgresql/data/pg_hba.conf

    sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /var/lib/postgresql/data/postgresql.conf

fi

##
# start postgreSQL and set default postgres password
#
echo -e "#####\n# Starting postgresql ..."
pg_ctl start -D /var/lib/postgresql/data

##
# create DB_USERNAME
#
echo -e "#####\n# Checking PostgreSQL user ..."
USR=`psql -U postgres -c '\du' | awk '/$DB_USERNAME/ { print $1 }'`
if [ "$USR" != "$DB_USERNAME" ]; then

    psql -U postgres -c "CREATE USER $DB_USERNAME WITH SUPERUSER ENCRYPTED PASSWORD '$DB_PASSWORD';"
    
fi

##
# create DB_DATABASE
#
echo -e "#####\n# Checking PostgreSQL database ..."
DB=`psql -U postgres -t -c 'select datname from pg_database' | awk '/$DB_DATABASE/ { print $1 }'`
if [ "$DB" != "$DB_DATABASE" ]; then

    psql -U postgres -c "CREATE DATABASE $DB_DATABASE;"

    psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DB_DATABASE TO $DB_USERNAME;"

fi

##
# configure nginx servers
#
echo -e "#####\n# Setting up nginx servers ..."
sed -i "s|HOST_API|$HOST_API|" /etc/nginx/nginx.conf
sed -i "s|HOST_APP|$HOST_APP|" /etc/nginx/nginx.conf

##
# configure xdebug
#
# echo -e "#####\n# Setting up Xdebug ..."
# sed -i -E "s|xdebug.remote_host=.+|xdebug.remote_host=$XDEBUG_HOST|" /etc/php8/conf.d/custom_xdebug.ini
# sed -i -E "s|xdebug.remote_port=.+|xdebug.remote_port=$XDEBUG_PORT|" /etc/php8/conf.d/custom_xdebug.ini
# sed -i -E "s|xdebug.idekey=.+|xdebug.idekey=$XDEBUG_IDE_KEY|" /etc/php8/conf.d/custom_xdebug.ini

##
# run compose
#
if [ ! -d /var/projects/api/vendor ]; then
    echo -e "#####\n# Installing dependencies ..."
    composer install
fi

##
# start php-fpm
#
echo -e "#####\n# Starting php ..."
php-fpm8

##
# start nginx
#
echo -e "#####\n# Starting nginx ..."
nginx