FROM alpine:edge

LABEL MAINTAINER = "Ian-FR <iiaan.fr@gmail.com>"

ARG PACKAGES="\
              nginx \
              postgresql \
              php8 \
              php8-bcmath \
              php8-curl \
              php8-dom \
              php8-fileinfo \
              php8-fpm \
              php8-gd \
              php8-mbstring \
              php8-openssl \
              php8-pdo \
              php8-pdo_pgsql \
              php8-pgsql \
              php8-phar \
              php8-session \
              php8-simplexml \
              php8-soap \
              php8-tokenizer \
              php8-xml \
              php8-xmlwriter \
              php8-zip "

RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    apk update && \
    apk add --no-cache $PACKAGES && \
    mv /usr/bin/php8 /usr/bin/php && \
    mv /usr/bin/phar8 /usr/bin/phar && \
    mv /usr/bin/phar.phar8 /usr/bin/phar.phar && \
    sed -i "s|127.0.0.1:9000|/run/php8/php-fpm.sock|" /etc/php8/php-fpm.d/www.conf && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === 'c31c1e292ad7be5f49291169c0ac8f683499edddcfd4e42232982d0fd193004208a58ff6f353fde0012d35fdd72bc394') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php --install-dir=bin --filename=composer && \
    php -r "unlink('composer-setup.php');" && \
    rm /etc/nginx/conf.d/default.conf && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /var/gdoorweb && \
    mkdir -p /run/nginx && \
    mkdir -p /run/php8 && \
    mkdir -p /run/postgresql && \
    mkdir -p /var/lib/postgresql/data

COPY ./config/php8/start /bin/start-server
COPY ./config/php8/nginx.conf /etc/nginx/nginx.conf
COPY ./config/php.ini /etc/php8/conf.d/custom_php.ini

RUN addgroup -S -g 1000 www && \
    adduser -S -u 1000 -G www -D www && \
    chmod +x /bin/start-server && \
    chown -R www:www /bin/start-server && \
    chown -R www:www /etc/nginx && \
    chown -R www:www /etc/php8 && \
    chown -R www:www /var/gdoorweb && \
    chown -R www:www /var/lib/nginx && \
    chown -R www:www /var/lib/php8 && \
    chown -R www:www /var/lib/postgresql && \
    chown -R www:www /var/log && \
    chown -R www:www /run/nginx && \
    chown -R www:www /run/php8 && \
    chown -R www:www /run/postgresql

VOLUME [ "/var/lib/postgresql/data" ]

WORKDIR /var/gdoorweb/backend

USER www

ENTRYPOINT [ "start-server" ]
