#!/bin/sh

##
# init PostgreSQL data when not exists
#
if [ ! -f "/var/lib/postgresql/data/PG_VERSION" ]; then

    echo "postgres" > /var/lib/postgresql/pg.pass
    
    initdb -D /var/lib/postgresql/data --username=postgres --pwfile=/var/lib/postgresql/pg.pass

    rm /var/lib/postgresql/pg.pass

    echo "host all all all md5" >> /var/lib/postgresql/data/pg_hba.conf

    sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /var/lib/postgresql/data/postgresql.conf

fi

##
# start postgreSQL and alter default postgres password
#
pg_ctl start -D /var/lib/postgresql/data

##
# create DB_USERNAME
#
if [ "psql -U postgres -c '\du' | awk '/$DB_USERNAME/ { print $1 }'" != "$DB_USERNAME" ]; then

    psql -U postgres -c "CREATE USER $DB_USERNAME WITH SUPERUSER ENCRYPTED PASSWORD '$DB_PASSWORD';"
    
fi

##
# create DB_DATABASE
#
if [ "psql -U postgres -t -c 'select datname from pg_database' | awk '/$DB_DATABASE/ { print $1 }'" != "$DB_DATABASE" ]; then

    psql -U postgres -c "CREATE DATABASE $DB_DATABASE;"

    psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DB_DATABASE TO $DB_USERNAME;"

fi

##
# configure nginx servers
#
sed -i "s/HOST_API/$HOST_API/" /etc/nginx/nginx.conf
sed -i "s/HOST_APP/$HOST_APP/" /etc/nginx/nginx.conf

##
# configure xdebug
#
sed -i "s/XDEBUG_HOST/$XDEBUG_HOST/" /etc/php7/conf.d/custom_xdebug.ini
sed -i "s/XDEBUG_PORT/$XDEBUG_PORT/" /etc/php7/conf.d/custom_xdebug.ini
sed -i "s/XDEBUG_IDE_KEY/$XDEBUG_IDE_KEY/" /etc/php7/conf.d/custom_xdebug.ini

##
# start php and nginx
#
php-fpm7
nginx