#!/bin/sh

##
# init PostgreSQL data when not exists
#
if [ ! -f "/var/lib/postgresql/data/PG_VERSION" ]; then

    echo "postgres" > /var/lib/postgresql/pg.pass
    
    initdb -D /var/lib/postgresql/data --username=postgres --pwfile=/var/lib/postgresql/pg.pass

    rm /var/lib/postgresql/pg.pass

    echo "host all all all md5" >> /var/lib/postgresql/data/pg_hba.conf

    sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /var/lib/postgresql/data/postgresql.conf

fi

##
# start postgreSQL and alter default postgres password
#
pg_ctl start -D /var/lib/postgresql/data

##
# create PG_USER
#
if [ "psql -U postgres -c '\du' | awk '/$PG_USER/ { print $1 }'" != "$PG_USER" ]; then

    psql -U postgres -c "CREATE USER $PG_USER WITH SUPERUSER ENCRYPTED PASSWORD '$PG_PASS';"
    
fi

##
# create PG_DB
#
if [ "psql -U postgres -t -c 'select datname from pg_database' | awk '/$PG_DB/ { print $1 }'" != "$PG_DB" ]; then

    psql -U postgres -c "CREATE DATABASE $PG_DB;"

    psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $PG_DB TO $PG_USER;"

fi

##
# configure default nginx server
#
DIR_APP=${DIR_APP////\\/}

sed -i "s/VHOST/$SERVER_NAME/" /etc/nginx/nginx.conf
sed -i "s/DIRAPP/$DIR_APP/" /etc/nginx/nginx.conf

##
# configure xdebug
#
sed -i "s/XDEBUG_HOST/$XDEBUG_HOST/" /etc/php7/conf.d/custom_xdebug.ini
sed -i "s/XDEBUG_PORT/$XDEBUG_PORT/" /etc/php7/conf.d/custom_xdebug.ini
sed -i "s/XDEBUG_IDE_KEY/$XDEBUG_IDE_KEY/" /etc/php7/conf.d/custom_xdebug.ini

##
# disable user and group php-fpm diretives
#
sed -i "s/user = nobody/;user = nobody/" /etc/php7/php-fpm.d/www.conf
sed -i "s/group = nobody/;group = nobody/" /etc/php7/php-fpm.d/www.conf

##
# start php and nginx
#
php-fpm7
nginx