FROM alpine:3.13

LABEL MAINTAINER = "Ian-FR <iiaan.fr@gmail.com>"

ARG PACKAGES="\
              composer \
              nginx \
              postgresql \
              php8-bcmath \
              php8-curl \
              php8-dom \
              php8-fileinfo \
              php8-fpm \
              php8-gd \
              php8-mbstring \
              php8-openssl \
              php8-pdo \
              php8-pdo_pgsql \
              php8-pgsql \
              php8-session \
              php8-simplexml \
              php8-soap \
              php8-tokenizer \
              php8-pecl-xdebug \
              php8-xml \
              php8-xmlwriter \
              php8-zip "

RUN apk update && \
    apk add --no-cache $PACKAGES && \
    rm /etc/nginx/conf.d/default.conf && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /var/projects && \
    mkdir -p /run/nginx && \
    mkdir -p /run/php8 && \
    mkdir -p /run/postgresql && \
    mkdir -p /var/lib/postgresql/data

COPY ./php/config/start /bin/start-server
COPY ./php/config/nginx.conf /etc/nginx/nginx.conf
COPY ./php/config/php.ini /etc/php8/conf.d/custom_php.ini

RUN addgroup -S -g 1000 www && \
    adduser -S -u 1000 -G www -D www && \
    chmod +x /bin/start-server && \
    chown -R www:www /bin/start-server && \
    chown -R www:www /etc/nginx && \
    chown -R www:www /etc/php8 && \
    chown -R www:www /var/projects && \
    chown -R www:www /var/lib/nginx && \
    chown -R www:www /var/lib/php8 && \
    chown -R www:www /var/lib/postgresql && \
    chown -R www:www /var/log && \
    chown -R www:www /run/nginx && \
    chown -R www:www /run/php8 && \
    chown -R www:www /run/postgresql

ADD --chown=www:www ./src/public /var/projects/api/public
ADD --chown=www:www ./src/public /var/projects/phpinfo
ADD --chown=www:www ./src/*.html /var/projects/app/

WORKDIR /var/projects/api

USER www

VOLUME [ "/var/lib/postgresql/data" ]

ENTRYPOINT [ "start-server" ]
